---

tasks:
  - name: Upgrade packages
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install git
    apt:
      name: git
      state: installed

  - name: Clone Retro-Pie repository
    git:
      repo: https://github.com/RetroPie/RetroPie-Setup.git
      depth: 1
      dest: /home/pi/RetroPie-Setup
      version: master

  - name: Make script executable
    file:
      path: ~/RetroPie-Setup/retropie_setup.sh
      mode: 0755

  - name: Run setup script
    command: sh ~/RetroPie-Setup/retropie_setup.sh
